runtime: java
env: flex
handlers:
- url: /.*
  script: this field is required, but ignored
resources:
  memory_gb: 4
endpoints_api_service:
  name: mutant.endpoints.mutant-230214.cloud.goog
  rollout_strategy: managed