runtime: java
env: flex
endpoints_api_service:
  name: mutant-230214
  rollout_strategy: managed
handlers:
- url: /.*
  script: this field is required, but ignored
health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 10
  unhealthy_threshold: 2
  healthy_threshold: 2